ARG NODE_VERSION=18

FROM node:$NODE_VERSION-buster AS base

WORKDIR /app

FROM base AS builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=server


FROM node:$NODE_VERSION-buster-slim AS production
WORKDIR /app

COPY --from=builder /app/packages/server/dist/ /app/
COPY --from=builder /app/packages/server/package.json /app/package.json
COPY --from=builder /app/packages/client/dist/ /app/dist/
RUN yarn install --production=true

ENV POSTGRES_PORT=${POSTGRES_PORT}
ENV SERVER_PORT=${SERVER_PORT}
ENV NODE_ENV="production"
EXPOSE $SERVER_PORT
CMD [ "node", "/app/index.js" ]
