export { type Coords, type GameObjectProps, GameObject } from './GameObject'
export { type SpriteProps, Sprite } from './Sprite'
export { Boundary } from './Boundary'
export { type FoodProps, Food } from './Food'
export { type BackgroundProps, Background } from './Background'
