export { loadTexture } from './loadTexture'
export { clearGame } from './clearGame'
export { rectangularCollision } from './rectangularCollision'
export { getGameTime } from './getGameTime'
export { drawGameTime } from './drawGameTime'
export { drawLife } from './drawLife'
export { drawScores } from './drawScores'
export { drawLevel } from './drawLevel'
export { getContextTextSettings } from './getContextTextSettings'
export { setHeroInitCoords } from './setHeroInitCoords'
export { type HeroParameters, getHeroParameters } from './getHeroParameters'
export { movementHero } from './movementHero'
export { eatingFood } from './eatingFood'
export { movementEnemy } from './movementEnemy'
