export { HomePage } from './Home'
export { initGamePage, GamePage } from './Game'
export { LoginPage } from './Login'
export { RegistrationPage } from './Registration'
export { initProfilePage, ProfilePage } from './Profile'
export { LeaderboardPage } from './Leaderboard'
export { ForumPage } from './Forum'
export { ForumTopicPage } from './ForumTopic'
export { ForumTopicCreationPage } from './ForumTopicCreation'
export { Error404Page } from './Error404'
